- contracts/src/AxelarGateway.sol
- contracts/src/BurnableMintableCappedERC20.sol
- contracts/src/Burner.sol
- contracts/src/ECDSA.sol
- contracts/src/ERC20.sol
- contracts/src/Ownable.sol
- replace privates with publics to remove function redundancy
- use `Contract.function.selector` instead of inline keccak
- simplify if-reverts into requires
- ERC20 constructor now takes decimals as an argument, making `_setupDecimals` redundant
- make `decimals` immutable (instead of a storage slot)
- more minor gas optimizations
> refactor: Cleanup

- contracts/src/AxelarGateway.sol
- contracts/src/BurnableMintableCappedERC20.sol
- contracts/test/AxelarGatewayMultisig.js
- contracts/test/AxelarGatewaySinglesig.js
No `Burner` contract needed (so much cheaper burning), and token contract owners cannot burn tokens that are not in specific "deposit addresses".
Burner contrat code still needed for the same of not creating breaking changes in `axelar-core`.
Left comments on how deposit addresses can be made globally consistent for any salt (all chains, all tokens).
> feat: Remove the need for `Burner`

- src/AdminMultisigBase.sol
- src/AxelarGateway.sol
- src/AxelarGatewayMultisig.sol
- src/AxelarGatewayProxy.sol
- src/AxelarGatewayProxyMultisig.sol
- src/AxelarGatewayProxySinglesig.sol
- src/AxelarGatewaySinglesig.sol
- src/BurnableMintableCappedERC20.sol
- src/Context.sol
- src/DepositHandler.sol
- src/ECDSA.sol
- src/ERC20.sol
- src/EternalStorage.sol
- src/MintableCappedERC20.sol
- src/Ownable.sol
- src/interfaces/IAxelarGateway.sol
- src/interfaces/IAxelarGatewayMultisig.sol
- src/interfaces/IAxelarGatewaySinglesig.sol
- src/interfaces/IERC20.sol
- test/AxelarGatewayMultisig.js
- test/AxelarGatewaySinglesig.js
1. Fix compiler version in pragma to be `0.8.9`
2. Change upgrade function signature to `function upgrade(address newImplementation, bytes32 newImplementationCodeHash, bytes calldata setupParams)` to make sure new implementation's codehash is as expected
> feat: upgrade verifies codehash

- src/AxelarGatewayMultisig.sol
- test/utils.js
```
ownerThreshold: 1, gasCost: 1160686
ownerThreshold: 2, gasCost: 1169661
ownerThreshold: 3, gasCost: 1178876
ownerThreshold: 4, gasCost: 1188325
ownerThreshold: 5, gasCost: 1198088
ownerThreshold: 6, gasCost: 1208143
ownerThreshold: 7, gasCost: 1218492
ownerThreshold: 8, gasCost: 1229095
ownerThreshold: 9, gasCost: 1240038
ownerThreshold: 10, gasCost: 1251108
ownerThreshold: 11, gasCost: 1262606
ownerThreshold: 12, gasCost: 1274233
ownerThreshold: 13, gasCost: 1286229
ownerThreshold: 14, gasCost: 1298476
ownerThreshold: 15, gasCost: 1311036
ownerThreshold: 16, gasCost: 1323795
ownerThreshold: 17, gasCost: 1336935
ownerThreshold: 18, gasCost: 1350349
ownerThreshold: 19, gasCost: 1363987
ownerThreshold: 20, gasCost: 1377873
ownerThreshold: 21, gasCost: 1392094
ownerThreshold: 22, …
```
> feat: require sorted signatures from owners/operators to improve gas cost

- src/AxelarGatewayMultisig.sol
- test/AxelarGatewayMultisig.js
> fix(Multisig): transferOperatorship using operatorEpoch

- src/AxelarGateway.sol
> fix(Gateway): using `abi.encode` for CallApprovedKey

- src/AxelarGateway.sol
- src/AxelarGatewayMultisig.sol
- src/interfaces/IAxelarGateway.sol
- src/interfaces/IAxelarGatewayMultisig.sol
- test/AxelarGatewayMultisig.js
- test/AxelarGatewaySinglesig.js
> feature(Gateway): getting admins, owners, operators and their thresholds

- .github/workflows/publish-to-npm.yaml
- .npmrc
Adding new CI workflow to automatically publish to npm. 
TODO: need to set Github private variable called NPM_TOKEN. If someone here wants to add it (the token is in 1pass as "npm token CI") or alternatively make me an admin on this repo, I can do it too
> Publish to npm ci

- contracts/AxelarGateway.sol
- contracts/AxelarGatewayProxy.sol
- contracts/interfaces/IAxelarGateway.sol
- test/AxelarDepositService.js
- test/AxelarGatewayMultisig.js
- test/gmp/GeneralMessagePassing.js
> fix(Gateway): addressing the important CodeArena reports

- contracts/auth/AxelarAuthWeighted.sol
- contracts/interfaces/IAxelarAuthWeighted.sol
- test/auth/AxelarAuthWeighted.js
> fix(AuthWeighted): improving error messages

- scripts/flatten-contracts.sh
Remove duplicate SPDX license identifiers and pragmas to simplify verifying contracts
> fix(scripts): remove duplicate identifiers/pragmas in flattener

- package.json
This PR allows node versions `16.x` and `18.x` to install this package since hardhat supports every currently maintained LTS node.js version as mentioned [here](https://hardhat.org/hardhat-runner/docs/reference/stability-guarantees#node.js-versions-support). The version is copied from the hardhat package [here](https://github.com/NomicFoundation/hardhat/blob/97d71e15e7b407ca1336b4c265aa2e9db5a98b53/packages/hardhat-core/package.json#L26), but I exclude version `14.x` because it won't be maintained anymore in the next few months.
> chore: support node version 16.x and 18.x

- test-evm-versions.bash
- test/AxelarDepositService.js
- test/AxelarGateway.js
- test/gmp/AxelarGasService.js
> test(ServiceProxy): should preserve Proxy bytecode

- hardhat.config.js
- package-lock.json
- package.json
- test/AxelarGateway.js
Codehash computation is different on polygon zkEVM, using poseidon hash function. Allow chain dependent bytecode hash retrieval.
> fix: compute codehash correctly for polygon zkevm

- package-lock.json
- package.json
- test/AxelarGateway.js
Updating the GMP SDK to `v4.0.0`
> chore: deps update

- .solhint.json
- .solhintignore
ERC20 files have a fixed bytecode. Ignore lint errors for them
> chore: ignore erc20 files for lint errors

- contracts/auth/MultisigBase.sol
- contracts/governance/InterchainGovernance.sol
- test/InterchainGovernance.js
- test/auth/MultisigBase.js
> fix(MultisigBase): gas usage optimizations

- contracts/gas-service/AxelarGasService.sol
- contracts/interfaces/IAxelarGasService.sol
- package-lock.json
- package.json
- test/gmp/AxelarGasService.js
> feat(GasService): adding express methods

- test/AxelarGatewayUpgrade.js
- test/BurnableMintableCappedERC20.js
- test/gmp/GeneralMessagePassing.js
Fixed some failing test cases encountered while testing for Cronos chain EVM compatibility
[AXE-1916](https://axelarnetwork.atlassian.net/browse/AXE-1916)
[AXE-1916]: https://axelarnetwork.atlassian.net/browse/AXE-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: test cronos integration [AXE-1916]

- README.md
- test/auth/AxelarAuthWeighted.js
Refactored the tests to reduce the number of signers required to 3 for live network testing
> refactor: tests for axelar auth weighted to reduce signers required [AXE-2323]

- contracts/gas-service/AxelarGasService.sol
- package-lock.json
- package.json
- test/gmp/AxelarGasService.js
> feat(GasService): updated estimation dependency

- contracts/test/TestRpcCompatibility.sol
- test/RpcCompatibility.js
https://axelarnetwork.atlassian.net/browse/AXE-4496
> feat: add rpc test to match logIndex

- test/RpcCompatibility.js
Add tests to validate block parent hashes. In the light of Flow behaviour explained as per [this](https://interoplabs.slack.com/archives/C021B409SG5/p1724405403164199?thread_ts=1724405178.231209&cid=C021B409SG5) thread.
> chore(test): add case for validating parent hash

- contracts/deposit-service/AxelarDepositService.sol
- contracts/gas-service/AxelarGasService.sol
- package-lock.json
- package.json
[AXE-6053](https://axelarnetwork.atlassian.net/browse/AXE-6053)
- Coverage remains same as before.
[AXE-6053]: https://axelarnetwork.atlassian.net/browse/AXE-6053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add missing setup implementation and bump up release version
