axelarnetwork/axelar-cgp-solidity

contracts/src/AxelarGateway.sol, contracts/src/AxelarGatewayMultisig.sol, contracts/src/AxelarGatewayProxyMultisig.sol, contracts/src/AxelarGatewayProxySinglesig.sol, contracts/src/AxelarGatewaySinglesig.sol, contracts/src/interfaces/IAxelarGateway.sol
- check signers outside of command loop
- use calldata where possible
=> feat: Reduce gas costs

contracts/package.json, contracts/waffle.json
=> chore: evm london version

src/AdminMultisigBase.sol, src/AxelarGateway.sol, src/AxelarGatewayMultisig.sol, src/AxelarGatewayProxy.sol, src/AxelarGatewaySinglesig.sol, src/ECDSA.sol, test/AxelarGatewaySinglesig.js
- where possible, to not change bytecode of tokens or deposit handlers
=> feat: Replace all requires with custom reverts

package.json
=> chore(npm): package name

package.json, src/AxelarGateway.sol, src/AxelarGatewayMultisig.sol, src/AxelarGatewaySinglesig.sol, src/interfaces/IAxelarExecutable.sol, src/interfaces/IAxelarGateway.sol, test/AxelarGatewaySinglesig.js
=> feature(ContractCall): flow improvements

package-lock.json, package.json, src/AxelarGateway.sol, src/AxelarGatewayMultisig.sol, test/AxelarGatewaySinglesig.js
=> feature(Gateway): freezing external tokens

LICENSE, README.md
- added license at the repo level
- moved build steps to the top in the README
=> repo(LICENSE): add license to the repo

package-lock.json, package.json
=> chore(npm): version bump

src/DepositHandler.sol, src/deposit-service/AxelarDepositService.sol, src/deposit-service/AxelarDepositServiceProxy.sol, src/deposit-service/DepositReceiver.sol, src/deposit-service/TestWeth.sol, src/gas-service/AxelarGasService.sol, src/gas-service/AxelarGasServiceProxy.sol, src/gmp-test/SourceChainSwapCaller.sol, src/interfaces/IAxelarDepositService.sol, src/interfaces/IAxelarGasService.sol, src/interfaces/IUpgradable.sol, src/interfaces/IWETH9.sol, src/util/Proxy.sol, src/util/Upgradable.sol, test/AxelarDepositService.js, test/gmp/AxelarGasService.js, test/gmp/GeneralMessagePassing.js
There are 3 main functions to this service: `sendToken`, `sendNative` and `withdrawNative`. Each of the functions are expecting the funds to be already transferred to a specific deposit address which is generated with following functions:
`depositAddressForSendToken`, `depositAddressForSendNative`, `depositAddressForWithdrawNative`. 
Here is a more detailed overview of the parameters they take:
```
function depositAddressForSendToken(
bytes32 nonce,
string calldata destinationChain,
string calldata destinationAddress,
string calldata tokenSymbol
) external view returns (address);
function sendToken(
bytes32 nonce,
string calldata destinationChain,
string calldata destinationAddress,
string calldata tokenSymbol
) external;
```
```
function depositAddressForSendNative(
bytes32 nonce,
string …
```
=> Feature: Deposit Service

contracts/gas-service/AxelarGasService.sol, contracts/interfaces/IAxelarGasService.sol
=> Fix: gas service sanity checks

contracts/ERC20.sol
=> fix(ERC20): removing beforeTokenTransfer

package-lock.json, package.json
=> chore(npm): v4.2.0 release

.gitignore, contracts/AxelarGateway.sol, contracts/interfaces/IAxelarGateway.sol, test/AxelarGateway.js
=> fix(Gateway): 6 hour mint limit

.github/workflows/lint.yaml, .github/workflows/publish-bytecode.yaml, .github/workflows/test.yaml, package-lock.json, package.json
=> Preparing release 4.3.1

contracts/AxelarGateway.sol, test/AxelarGateway.js
* fix: prevent the same deposit handler from being deployed
multiple times in the same tx
* add comments
=> fix: prevent the same deposit handler from being deployed multiple times in the same tx (#162)

.github/workflows/lint.yaml, .github/workflows/test.yaml, contracts/util/Proxy.sol, info/mainnet.json, info/testnet.json, package.json, scripts/deploy-upgradable.js, scripts/upgradable.js
- deploy service contracts for all chains
=> chore(scripts): deploy service contracts

test/gmp/AxelarGasService.js
Added test for addExpressGas and addNativeExpressGas
=> test(express-gas): expand test coverage

info/mainnet.json, info/testnet.json
- Add filecoin mainnet/testnet configs
- Add Base testnet config
=> feat: add filecoin and base configs

scripts/deploy-upgradable.js
Quick fix to deploy deposit service until GMP express branch gets merged
=> fix: deploy deposit service

contracts/gas-service/AxelarGasService.sol, contracts/interfaces/IAxelarGasService.sol, test/gmp/AxelarGasService.js
https://axelarworkspace.slack.com/archives/C02T1BNNS9Y/p1683245157722149
=> feat: added a separate refund method that takes txHash/logIndex and emit a Refunded event

.gitignore, hardhat.config.js, package-lock.json, package.json, test/AxelarDepositService.js, test/AxelarGateway.js, test/gmp/AxelarGasService.js, test/utils.js
Generate code coverage report via `npm run coverage`
=> feat: add code coverage tool

.solcover.js, contracts/governance/InterchainGovernance.sol, contracts/test/GovernanceTarget.sol, contracts/test/TestInterchainGovernance.sol, test/InterchainGovernance.js
This PR contains unit tests and NatSpec documentation for the InterchainGovernance contract.
Solidity Coverage Report for InterchainGovernance.sol:
100% Statements 17/17 | 92.86% Branches 13/14 | 80% Functions 4/5 | 91.3% Lines 21/23
[AXE-1165](https://axelarnetwork.atlassian.net/browse/AXE-1165)
[AXE-1165]: https://axelarnetwork.atlassian.net/browse/AXE-1165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: unit tests and natspec docs for governance module

contracts/AxelarGateway.sol, contracts/interfaces/IAxelarGateway.sol, contracts/interfaces/IGovernance.sol, test/AxelarDepositService.js, test/AxelarGateway.js, test/gmp/GeneralMessagePassing.js, test/utils.js
PR for test changes due to governance module gateway integration.
=> feat: refactor tests for governance gateway integration

contracts/governance/AxelarServiceGovernance.sol, contracts/interfaces/IAxelarServiceGovernance.sol, contracts/test/Target.sol, contracts/test/TestServiceGovernance.sol, test/AxelarServiceGovernance.js, test/InterchainGovernance.js
This PR contains unit tests and NatSpec documentation for AxelarServiceGovernance.
Solidity Test Coverage Report for AxelarServiceGovernance.sol:
100% Statements 17/17 | 92.86% Branches 13/14 | 100% Functions 3/3 | 95% Lines 19/20
*Showing cancel multisig approval as not covered even though there is a test case for that branch
*Gateway tests are failing but should pass once this branch is merged into one that contains the updated gateway test script
=> feat: service governance tests and documentation

.github/workflows/publish-to-npm.yaml, .gitignore, package-lock.json, package.json, test/AxelarGateway.js
=> chore: improving release process and updating dependencies

DESIGN.md, README.md
=> fix: typos

.github/workflows/publish-to-npm.yaml, package-lock.json, package.json
=> build(npm): building interfaces and version bump 

contracts/AxelarGateway.sol, test/AxelarGateway.js
PR for AxelarGateway NatSpec documentation.
Note: Will fix bytecode tests once NatSpec documentation is finalized.
=> feat: gateway natspec docs

.github/workflows/publish-bytecode.yaml, .github/workflows/publish-to-npm.yaml, package-lock.json, package.json
=> ci(npm): packaging only necessary artifacts

.gitignore, contracts/AxelarGateway.sol, contracts/deposit-service/AxelarDepositService.sol, contracts/deposit-service/ReceiverImplementation.sol, contracts/gas-service/AxelarGasService.sol, contracts/interfaces/IAxelarGasService.sol, package-lock.json, package.json, test/AxelarGateway.js, test/gmp/AxelarGasService.js
=> SafeNativeTransfer and Gas Service 0 payments

contracts/AxelarGateway.sol, package-lock.json, package.json, test/AxelarGateway.js
=> fix(Gateway): deploy token event

README.md
Updated 2 steps in live network testing section for better understanding on running tests on a new chain
=> docs: live network testing [AXE-1984]

contracts/AxelarGateway.sol, package-lock.json, package.json, test/AxelarGateway.js
[AXE-2316]
[AXE-2316]: https://axelarnetwork.atlassian.net/browse/AXE-2316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(gateway): added ContractCallExecuted event

.github/CODEOWNERS, .github/workflows/lint.yaml, .github/workflows/publish-bytecode.yaml, .github/workflows/publish-to-npm.yaml, .github/workflows/release-dry-run.yaml, .github/workflows/release.yaml, .github/workflows/slither.yml, .github/workflows/test.yaml, .prettierrc, hardhat.config.js, package-lock.json, package.json, slither.config.json
backport #266 #265 #264 #261 #263
=> chore: backport config changes and bump version

test/RpcCompatibility.js
Jira: https://axelarnetwork.atlassian.net/browse/AXE-3064
Update the comment to explain that this test is to check if the gas requirements for a new chain align with the Ethereum requirements.
Added a test to check transaction goes through using estimated gas.
=> refactor: update eth_estimateGas test comment

.github/workflows/codecov.yaml, .github/workflows/conventional-commits.yaml, .github/workflows/lint.yaml, .github/workflows/slither.yaml, .github/workflows/test.yaml
Integrate codecov as per [AXE-3415](https://axelarnetwork.atlassian.net/jira/software/c/projects/AXE/boards/21?selectedIssue=AXE-3415)
[AXE-3415]: https://axelarnetwork.atlassian.net/browse/AXE-3415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add codecov action

.github/workflows/slither.yaml, contracts/test/gmp/SourceChainSwapCaller.sol, test/AxelarGatewayUpgrade.js
Added gas options to test for AxelarGatewayUpgrade
https://axelarnetwork.atlassian.net/browse/AXE-3659
=> refactor: add gas options to gateway upgrade test

.github/workflows/slither.yaml, contracts/gas-service/AxelarGasService.sol, contracts/test/gmp/SourceChainSwapCaller.sol, package-lock.json, package.json, test/AxelarGatewayUpgrade.js, test/gmp/AxelarGasService.js
=> chore: releasing v6.3.1

.github/workflows/release.yaml
- Update the way how the package version is being retrieved
=> ci: update the way how the package version is being retrieved
